name: Karate API Tests
run-name: ${{ github.actor }} is testing demand demo workflow
on:
  workflow_dispatch:
    inputs:
      YOUR_TAG:
        type: choice
        required: true
        options:
          - regression
          - getJobApi
          - postJobApi
          - deleteJobApi
        default: "regression"
        description: "Your_role"
jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      java-version: '21'

  run-karate-test:
    runs-on: windows-latest
    needs: call-reusable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Run regression tests
        run: mvn test -Dtest=TestRunner#runTest "-Dkarate.options=--tags @${{ github.event.inputs.YOUR_TAG}}"

      - name: Upload Karate report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: target/karate-reports/